### ISSUE TITLE
可能是几个好的建议:)

### ISSUE THREAD

**Issue by d1y** [MrYang-Web/MrYang-Web.github.io#1]
## Github上静态文件处理

github在国内的速度堪忧,所以加载文件会很慢,如果所有的文件都存在github上,会造成 `git` 仓库的巨大化

![](https://i.loli.net/2019/05/27/5ceb64d45bdb188034.png)

这样很不利于用户体验和个人的开发\(假设场景: 你跑到网吧去 `clone` 这个仓库  `50kb/s` \)

给出的建议就是

1. 上图床
1. 上 `CDN` 
1. ...

图床是我比较推荐的,这里推荐使用 `http://sm.ms` \(只能上传图片文件\),如果是其他文件类型,推荐上 `http://catbox.moe` \(速度不咋地\),还有其他的会在下文贴出,然后就是上 `CDN` ,这里推荐的 `CDN` ,只是为了解决 `github` 的访问速度问题,使用场景如下:

> 假设 你的图片觉得位置为:  [https://github.com/MrYang\-Web/MrYang\-Web.github.io/blob/master/imgs/1.jpg](https://github.com/MrYang-Web/MrYang-Web.github.io/blob/master/imgs/1.jpg), 相应的你的图片位置就为: 

https://cdn.jsdelivr.net/gh/MrYang\-Web/MrYang\-Web.github.io/imgs/1.jpg

既:

 `https://cdn.jsdelivr.net/gh/你的用户名/你的项目/相对路径` 

推荐使用正则式的方式一键修改路径

## 音乐接口

在 `github` 放置音频真的很不明智,导致 `repo` 非常大,所以,假设你要引用 `网易云音乐` 的话可能直接引入  `302` 跳转的图片,栗子:

![](https://i.loli.net/2019/05/27/5ceb68db4078f93752.png)

拿到歌曲 `id` ,在你的  `audio`  src里直接引入链接:

    

http://music.163.com/song/media/outer/url?_id_=_id_.mp3

 `id` 既找到的 `id`

**Comment by MrYang-Web** [comment]
已经找到解决办法，教师培训系统提供了应该是不受限制的上传空间，并且带宽很足。不想买云服务器，就差自己搭建服务器了。被设计大赛逼得没办法了，想到体制内还有这么个奇葩的平台存在，教师独享哟(*^▽^*)

**Comment by d1y** [comment]
> 已经找到解决办法，教师培训系统提供了应该是不受限制的上传空间，并且带宽很足。不想买云服务器，就差自己搭建服务器了。被设计大赛逼得没办法了，想到体制内还有这么个奇葩的平台存在，教师独享哟(_^▽^_)

一切静态资源不上`CDN`都是耍流氓
